
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	# DO NOT ADD HERE, CREATE A SPECIFIC FILE IN HARDWARE FOLDER
}
