
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	systemd.services.lact = {
		description = "intelGPU Control Daemon";
		after = ["multi-user.target"];
		wantedBy = ["multi-user.target"];
		serviceConfig = {
			ExecStart = "${pkgs.lact}/bin/lact daemon";
		};
		enable = true;
	};
	hardware.cpu.intel.updateMicrocode = true; #lib.mkDefault;
	hardware.graphics = {
		enable = true;
		extraPackages = with pkgs; [
			# optional tooling {
			intel-compute-runtime # OpenCL (NEO) + level ero for Arc/Xe
			# required fro modern intel GPUs {
			intel-media-driver # VA-API (iHD) userspace WILL CAUSE OBS TO CRASH IF RESIZE_BAR IS NOT ENABLED, EVEN IF ENABLED DOUBLE CHECK YOU WILL THANK ME LATER
			vpl-gpu-rt # openVPL (QSV) runtime
			# onevpl-intel-gpu # outdated
			# }
		];
	};
}
