# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  # may help if FFmpg/vaapi/qsv init fails
  hardware.enableRedistributableFirmware = true;
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f54c584c-e525-42b7-9d36-ba4156f27a73";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/39CC-3D64";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fe95212b-92fc-4b1d-bba0-cada1a0242a4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  services.xserver.videoDrivers = [ "intel" ];

  hardware.enableAllFirmware = true; #new
  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "iHD"; # prefer modern iHD backend
  };
  #services.xserver.extraGroups = ["video"]; #POTENTIAL

}
