# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # --- ADD THESE BACK ---
  fileSystems."/" = { 
    device = "/dev/disk/by-uuid/f54c584c-e525-42b7-9d36-ba4156f27a73";
    fsType = "ext4";
  };

  fileSystems."/boot" = { 
    device = "/dev/disk/by-uuid/39CC-3D64";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ 
    { device = "/dev/disk/by-uuid/fe95212b-92fc-4b1d-bba0-cada1a0242a4"; } 
  ];
  # -----------------------

  hardware.enableAllFirmware = true; 
  hardware.enableRedistributableFirmware = true;
  boot.extraModulePackages = [ ];
  hardware.firmware = [ pkgs.linux-firmware ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
