


# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	#boot.kernelParams = [ "i915.enable_guc=3" ];
	boot.kernelParams = [ "i915.force_probe=e20b" "xe.force_probe=e20b" ]; # NEW
	boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
	boot.initrd.kernelModules = [ "xe" ];
	boot.kernelModules = [ 
		"kvm-intel" 
		"rtw89_8852ce" # get wifi drivers to work for Realtek Wifi RTL8852CE
	];

	# Use latest kernel.
	boot.kernelPackages = pkgs.linuxPackages_latest;

	# FOR VIRTUAL CAMERA SUPPORT with obs-studio
	# boot.extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];
	# boot.kernelModules = [ "v4l2loopback" ];
}
