


# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	# Use latest kernel.
	boot.kernelPackages = pkgs.linuxPackages_latest;


# 	  # 2. Tell the Kernel to use it
# 	  boot.kernelParams = [
# 	    "xe.force_probe=e20b"
# 	    "video=DP-1:1920x1080@60D"                # The 'e' forces it to 'enabled'
# 	  ];

	# Ensure the EDID file is actually in the initrd so the driver sees it at boot
	# boot.initrd.extraFiles."/lib/firmware/edid/1920x1080.bin".source = ./path/to/your/edid.bin;
	boot.initrd.availableKernelModules = [ 
		"ahci" 
		"sd_mod" 
		"usbhid" 
		"usb_storage" 
		"xhci_pci" 
	];

	boot.initrd.kernelModules = [ 
		"xe" 
		"mt7921e" 
	];

	boot.kernelModules = [ 
		"kvm-intel"    # for intel gpu support
		"rtw89_8852ce" # get wifi drivers to work for Realtek Wifi RTL8852CE
		"v4l2loopback" # for obs virtual camera
		"r8125"
	];

	boot.blacklistedKernelModules = [ "r8169" ];

	# FOR VIRTUAL CAMERA SUPPORT with obs-studio
	boot.extraModulePackages = with config.boot.kernelPackages; [ 
		r8125
		v4l2loopback 
	];
}
